import re
Pattern_un=r"[A-z,0-9]*"
Pattern_psw=r"[A-z,0-9@#$%^&+]{6,20}$"
Pattern_name=r"^[A-Z][a-z]*$"
Pattern_email=r"[A-z0-9]+.+@+[A-z]+.+[a-z]$"
Pattern_phone="^[0-9]{10}$"
Pattern_lic="[A-Z]{2}[0-9]{2}[0-9]{11}$"
Pattern_adhr=r"[0-9]{12}$"
Pattern_city=r"^[A-Z,a-z]+$"
Pattern_pincode=r"^[0-9]{6}$"
Pattern_state=r"^[A-Z,a-z]+$"
Pattern_Company_name=r"^[A-Z,a-z]+$"
Pattern_mdl=r"[A-z][0-9]*"
Pattern_Color=r"^[A-Z,a-z]+$"
Pattern_Price=r"^[0-9,A-z]+$"
Patter_Fuel=['Petrol','Diesel','Ev','Cng']